name: flutter_connectivity_hook
description: Flutter Connectivity Hook package
version: 0.2.5

publish_to: "none"

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_connectivity:
    git:
      url: https://github.com/Iconica-Development/flutter_connectivity
      ref: 0.2.4
  flutter_hooks: ^0.20.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 6.0.0

flutter:
